export const MAILGUN_CONFIG_TOKEN = Symbol('SK_MAILGUN_CONFIG_TOKEN');
export const MAILGUN_CLIENT_TOKEN = Symbol('SK_MAILGUN_CLIENT_TOKEN');

export const SENDGRID_CONFIG_TOKEN = Symbol('SK_SENDGRID_CONFIG_TOKEN');
export const SENDGRID_CLIENT_TOKEN = Symbol('SK_SENDGRID_CLIENT_TOKEN');
