export enum AuthType {
  LOCAL = 'LOCAL',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  LINKEDIN = 'LINKEDIN',
  GITHUB = 'GITHUB',
  MICROSOFT = 'MICROSOFT',

  SAML_TENANT = 'SAML_TENANT',
  OPENID_CONNECT_TENANT = 'OPENID_CONNECT_TENANT',
}
