environment = "prod"
aws_region = "eu-central-1"
repository_name = "softkit-core"
project_name = "docs"
org_name = "softkitit"
tf_state_file_name = "prod-docs-terraform.tfstate"
dynamo_db_table_name = "prod-softkitit-docs"
s3_bucket_name = "prod-softkitit-docs"
