export const CUSTOM_TOKEN_FTP_CLIENT_CONFIG_TOKEN = Symbol(
  'CUSTOM_TOKEN_FTP_CLIENT_CONFIG_TOKEN',
);
export const NO_AUTO_CONNECT_FTP_CLIENT_CONFIG_TOKEN = Symbol(
  'NO_AUTO_CONNECT_FTP_CLIENT_CONFIG_TOKEN',
);
