import { BaseJobExecution, JobExecution } from '../../entity';
import { BaseEntityHelper, BaseRepository } from '@softkit/typeorm';
import { BaseEntityService } from '@softkit/typeorm-service';

export abstract class AbstractJobExecutionService<
  T extends BaseJobExecution = JobExecution,
  FIELDS_REQUIRED_FOR_UPDATE = Pick<T, 'id'>,
  EXCLUDE_AUTOGENERATED_FIELDS extends BaseEntityHelper = BaseEntityHelper,
> extends BaseEntityService<
  T,
  'id',
  BaseRepository<T, 'id'>,
  FIELDS_REQUIRED_FOR_UPDATE,
  EXCLUDE_AUTOGENERATED_FIELDS
> {}
