import { BaseJobExecution, JobExecution } from '../../entity';
import { BaseTrackedEntityHelper } from '@softkit/typeorm';
import { BaseTrackedEntityService } from '@softkit/service-api';
import {
  AbstractRepository,
  ITrackedRepository,
} from '@softkit/persistence-api';
import { JobExecutionRepository } from '../../repository';

export abstract class AbstractJobExecutionService<
  T extends BaseJobExecution = JobExecution,
  FIELDS_REQUIRED_FOR_UPDATE extends keyof T = 'id',
  AUTOGENERATED_FIELDS extends keyof T = keyof BaseTrackedEntityHelper | 'id',
  REPOSITORY extends AbstractRepository<
    T,
    'id',
    unknown,
    FIELDS_REQUIRED_FOR_UPDATE,
    AUTOGENERATED_FIELDS
  > &
    ITrackedRepository<T, 'id', unknown> = JobExecutionRepository<
    T,
    'id',
    FIELDS_REQUIRED_FOR_UPDATE,
    AUTOGENERATED_FIELDS
  >,
> extends BaseTrackedEntityService<
  T,
  'id',
  REPOSITORY,
  FIELDS_REQUIRED_FOR_UPDATE,
  AUTOGENERATED_FIELDS
> {}
