name: Build and Deploy apps

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - prod
        description: "Environment to deploy apps to"
        default: "prod"

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.define-envs.outputs.environment }}

    steps:
      - name: Base env info
        run: |
          echo ENVIRONMENT=${{ inputs.environment || 'prod' }} >> $GITHUB_ENV

      - name: Define envs information
        id: define-envs
        run: |
          echo environment=${{ env.ENVIRONMENT }} >> $GITHUB_OUTPUT

  build-apps:

    needs: [ prepare ]
    runs-on: ubuntu-latest
    outputs:
      affected-projects: ${{ steps.get-affected-projects.outputs.affected-projects }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0

      - name: Verify if last release tag exists, and define nx command to use
        id: nx
        run: |
           echo exec-cmd="npx nx affected --base=last-release" >> $GITHUB_OUTPUT
           echo show-apps="npx nx show projects --json --type app --affected --base last-release" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install environment
        run: yarn install

      - name: Get affected projects
        id: get-affected-projects
        run: echo affected-projects=$(${{ steps.nx.outputs.show-apps }} --with-target build-fe) >> $GITHUB_OUTPUT

      - name: Build apps
        run: ${{ steps.nx.outputs.exec-cmd }} -t build-fe

#      readme needed because of limitation of upload artifact action
#      https://github.com/actions/upload-artifact/issues/174
      - name: Upload builds
        uses: actions/upload-artifact@v4
        if: steps.get-affected-projects.outputs.affected-projects != '[]'
        with:
          name: build
          path: apps/*/build
          if-no-files-found: error

  apply-tf-app-changes:
    needs: [ prepare, build-apps ]
    if: ${{ needs.build-apps.outputs.affected-projects != '[]' && needs.build-apps.outputs.affected-projects != ''}}

    strategy:
      matrix:
        project: ${{ fromJson(needs.build-apps.outputs.affected-projects) }}
    uses: softkitit/github-actions-terraform/.github/workflows/cd-apply-terraform-changes.yml@main
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      terraform-folder: apps/${{ matrix.project }}/terraform
    secrets: inherit

  deploy-app:
    needs: [ prepare, apply-tf-app-changes, build-apps ]
    strategy:
      matrix:
        project: ${{ fromJson(needs.build-apps.outputs.affected-projects) }}

    uses: softkitit/github-actions-terraform/.github/workflows/cd-deploy-to-s3.yml@main
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      s3-bucket-name: ${{ github.event.repository.name }}-${{ needs.prepare.outputs.environment }}-${{ matrix.project }}-origin
      cloudfront-origin-name: ${{ github.event.repository.name }}-${{ needs.prepare.outputs.environment }}-${{ matrix.project }}
      website-content: build
      folder-to-upload: ${{ matrix.project }}/build
    secrets: inherit





