name: Publish Libraries

on:
  push:
    branches:
      - main

concurrency:
  group: single-group
  cancel-in-progress: false

jobs:
  publish:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          node-version: 20.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install environment
        run: yarn install

      - name: Generate changelog and bump versions
        run: |
          git config --local user.email "automation@softkit.dev"
          git config --local user.name "GitHub Auto Release"
          npx nx affected --target version --noVerify --push --skipRootChangelog true --base=last-release --changelogHeader "Softkit Core Libraries Changelog" --skipCommitTypes=docs,ci --parallel=false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Tag last-release
        run: |
          git tag -fa last-release -m "Last release"
          git push origin last-release --force --no-verify
